<?xml version='1.0' encoding='utf-8'?>
<!-- comment... -->
<!DOCTYPE priceList [
	<!ELEMENT priceList (coffee)+>
	<!ELEMENT coffee (name, price)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	]>
  <priceList>
    <coffee>
       <name> Mocha Java </name>
       <price> 11.95 </price>
    </coffee>
    <coffee>
       <name> Sumatra </name>
       <price> 12.50 </price>
    </coffee>
  </priceList>
